FROM python:3.8-slim-buster

EXPOSE 8501

RUN apt-get update && apt-get install -y \
    build-essential \
    software-proprties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY ./app

WORKDIR /app

RUN pip3 intall -r requirements.txt

ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", ""]